### PR TITLE
Readme: added 2 new behaviours available

### PR DESCRIPTION
**Pull request by nicooprat**
Hope it helps!

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/zimme/meteor-collection-behaviours/pull/20" target="_blank">ReviewNinja

**Comment by zimme** [comment]
Nice, this is why I wanted to have the core and the behaviours as separate packages. =)

I'll just have a look at the packages before accepting this PR. I wanna make sure all behaviours I promote have proper documentation and the intention of the behaviour is quite clear and isn't a duplicate of another behaviour.

Good job.

**Comment by nicooprat** [comment]
Yes, that was a good idea! Too bad there's not more behaviours available! (for now).

Ya you better give a look at my code, I'm sure you'll find some ways to improve it :)

Thanks for your work and your time.

**Comment by zimme** [comment]
I'm truly sorry I didn't take the time to review and add this as I'm sure the behaviours you created was solving a real problem.

I've chosen to rethink the approach of the behaviours to have a simpler design and not to rely on a "central" behaviours package. https://github.com/meteor-collectionbehaviours.

I'm closing this and I'd be happy to discuss the behaviours you've created to see if we can add it to the other organization.

**Comment by nicooprat** [comment]
No problem, the new code looks even better. Hope I'll find some time to port my behaviours to this new base!

**Pull request closed without merging**
